name: firebase_ui_oauth
description: Firebase UI widgets for authentication & OAuth
publish_to: 'none'
version: 1.5.0
homepage: https://github.com/firebase/FirebaseUI-Flutter/tree/master/packages/firebase_ui_oauth

environment:
  sdk: ">=2.18.0 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  desktop_webview_auth: ^0.0.14
  firebase_auth: ^4.17.5
  flutter_svg: ^2.0.9
#  firebase_ui_auth: ^1.13.0
#  firebase_ui_shared: ^1.4.1

#  firebase_ui_auth:
#    path: ../firebase_ui_auth
#  firebase_ui_shared:
#    path: ../firebase_ui_shared

  firebase_ui_auth:
    git:
      url: https://github.com/alexandr-zherebtsov/FirebaseUI-Flutter.git
      path: packages/firebase_ui_auth/
      ref: feature/UI-builders
  firebase_ui_shared:
    git:
      url: https://github.com/alexandr-zherebtsov/FirebaseUI-Flutter.git
      path: packages/firebase_ui_shared/
      ref: feature/UI-builders

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

false_secrets:
  - "/example/**/google-services.json"
  - "/example/**/firebase_options.dart"
  - "/example/**/GoogleService-Info.plist"
  - "/example/lib/config.dart"

flutter:
